jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

spring:
  application:
    name: localens
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  datasource:
    url: jdbc:mysql://localens.cpc8gqku4ew1.ap-northeast-2.rds.amazonaws.com:3306/localens
    username: localens
    password: localens
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

influxdb:
  url: http://15.165.37.65:8086
  token: duNMs9CKGD6w2JEiQBlSx7Yd6h7d2b1Yr_c063X3H-WK6DUVMc0JQxymh8xlw8j0i_4FEV3HwNa_JrGEuU0zBQ==
  org: dev
  bucket: hourly
  measurement: visitor_data

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

cloud:
  aws:
    credentials:
      access-key: localens
      secret-key: localens0629!
    region:
      static: ap-northeast-2
    s3:
      bucket: localens-image